import { Col, Content, Header, Layout, Row, Sider, Title } from '@/components/antd';
import './globals.css'
import type { Metadata } from 'next'
import { ReactNode } from 'react';
import dynamic from 'next/dynamic'
import MenuHeader from '../components/menu-header';

const MenuRoot = dynamic(() => import("@/components/menu-root"), { ssr: false })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body>
        <>
          <Layout
            style={{
              height: '100vh'
            }}
          >
            <Header
              style={{
                background: 'rgb(255, 255, 255)',
                borderBottom: '1px solid rgba(5, 5, 5, 0.06)'
              }}
            >
              <Row justify="space-between" align="middle">
                <Col span={4}>
                  <Title level={3} style={{
                    margin: 0
                  }}>Bada Studio</Title>
                </Col>
                <Col span={1}>
                  <MenuHeader />
                </Col>
              </Row>
            </Header>
            <Layout>
              <Sider
                style={{
                  background: 'rgb(255, 255, 255)',
                }}
              >
                <MenuRoot />
              </Sider>
              <Layout>
                <Content
                >
                  {children}
                </Content>
              </Layout>
            </Layout>
          </Layout>
        </>
      </body>
    </html>
  );
}
