import { Content, Header, Layout, Sider, Title } from '@/components/antd';
import './globals.css'
import type { Metadata } from 'next'
import { ReactNode } from 'react';
import dynamic from 'next/dynamic'

const MenuRoot = dynamic(() => import("@/components/menu-root"), { ssr: false })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body>
        <>
          <Layout
            style={{
              height: '100vh'
            }}
          >
            <Header
              style={{
                background: 'rgb(255, 255, 255)',
                borderBottom: '1px solid rgba(5, 5, 5, 0.06)'
              }}
            >
              <Title level={3}>Bada UI</Title>
            </Header>
            <Layout>
              <Sider
                style={{
                  background: 'rgb(255, 255, 255)',
                }}
              >
                <MenuRoot />
              </Sider>
              <Layout>
                <Content
                >
                  {children}
                </Content>
              </Layout>
            </Layout>
          </Layout>
          {/* <Script
            crossOrigin='anonymous'
            src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js" /> */}
        </>
      </body>
    </html>
  );
}
